server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/menu_db


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

