server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reports_db
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: report-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            value.default.type: Report.service.Repost.Service.Event.DailyReportsDTO
            trusted.packages: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
